### ISSUE TITLE
Help me understand the parents search :)

### ISSUE THREAD

**Issue by matth** [bbc/rdfsim#1]
Heya,

Just having a go at implementing a Scala version of this codebase and getting a bit stuck on my understanding of the parents method. 

I see the Skos hierarchy as a graph and the parents method as a breadth first traversal of this graph up to a specified depth. Does this sound like a reasonable assumption to make? 

I am not sure that this method quite does that though as I see some differences in the results with my algorithm. I think that this method will only do a depth first traversal up until the point where length(done) = max depth, which means the traversal can terminate early.

If this is the case then could it lead to a situation where if the first category searched has more than 10 anscestors then that will fill the "done" array and the next direct category will not be searched further. An example to illustrate this ...
1. London has six direct parents, the first to get searched on my install of rdfsim is Capitals_in_Europe, which has more than 10 ancestors and fills the done array. 
2. The next category for London is M4_corridor, one the parents for this is Regions_of_England which I would expect to be searched as it is only a depth of 2 away from London (London -> M4 corridor -> Regions of England). 
3. However, I do not see Regions of England in the results, because by the time M4 corridor is searched the done array is already full.

Is this a bug in the code or is it my understanding that's broken? I noticed this at first as my algorithm was returning many more parents than this one :)

Cheers,

Matt

**Comment by moustaki** [comment]
Hello!

That might be a bug indeed in the max_depth termination clause, thanks for spotting it! A simple fix would be to make sure what's passed to the recursive parents call is a copy of the done array (line 83 of space.py). I'll give it a shot next week :)

Cheers,
y

**Comment by matth** [comment]
Thanks for the reply :) It might be the case - I was wandering why I couldn't get my results to match. 

The downside is that the breadth first traversal method in my code takes a lot longer to execute than yours, even using Scala which "should" be faster than Python I think :) I'll take another look at my code though to see if it can be improved. 

On the other hand there are a lot more results returned with a the breadth first traversal to depth 10, and usually by the time you've gone that deep you get to a lot of very broad concepts (e.g. Humans, Society). So I wonder if with more low order ancestors being returned if the depth can be reduced.

**Comment by matth** [comment]
Here's my scala version so far, the parents function does a breadth first search (while loops for speed not beauty). 

https://gist.github.com/618a0dcd4f1e6a8f17a8

With a depth of 5 it can build 1000 randomly selected vectors in ~ 0.7s, or 0.4s if I use some of scala's concurrency optimisations. Would be interested to see how it compares with python and with a web service in mind, how many vectors I'd need to create to disambiguate terms in a typical news article :)

Anyhow, have a great xmas!!

**Comment by moustaki** [comment]
Just had a closer look, and it is indeed a bug! I used your example as a test case and fixed it as mentioned above.

https://github.com/bbcrd/rdfsim/commit/df4f3143d075f9edf9b97ae01e750e14d37af49e

Thank you!

**Comment by moustaki** [comment]
Not really comparable, but on my laptop and with the above patch I am getting ~1.9s for London for a max_depth of 10 (7880 results), and 0.019s for a max_depth of 5 (1052 results).

**Comment by matth** [comment]
Thanks! Looks like it does impact the speed a bit though. FWIW I amended my algorithm a little to use integers as the keys and values for the direct parents hash table, seemed to improve both speed and memory by around ~40%

Still looking into integrating this + dbpedia lookup into the juicer app, have a suspicion the results could be quite good but nothing concrete yet :)
